TYPE E_Runtime_Observer_Deny_Reason :
(
    RODR_NONE := 0,
    RODR_NO_ENABLE_REQUEST := 10,
    RODR_BOOTSTRAP_DISABLED := 100,
    RODR_PASSIVE_MODE_DISABLED := 110,
    RODR_READONLY_MODE_DISABLED := 120,
    RODR_GOVERNANCE_UNLOCKED := 130,
    RODR_RUNTIME_AUTHORITY_ENABLED := 140,
    RODR_WRITABLE_EXPORTS_ENABLED := 150
);
END_TYPE
