TYPE E_Runtime_Observer_Lifecycle_State :
(
    ROS_INACTIVE := 0,
    ROS_AUTHORIZATION_PENDING := 10,
    ROS_AUTHORIZATION_DENIED := 20,
    ROS_STABILIZATION := 30,
    ROS_OPERATIONAL := 40,
    ROS_ROLLBACK := 50,
    ROS_FAULTED := 900
);
END_TYPE
